# Docker profile properties
spring.datasource.url=jdbc:h2:file:/app/data/finflow-db
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JWT
jwt.secret=mysecretkeymysecretkeymysecretkey123
jwt.expiry.milliseconds=3600000

# Resilience4j
resilience4j.retry.instances.otpRetry.max-attempts=3
resilience4j.retry.instances.otpRetry.wait-duration=1s
